---
# This is actually invoked from a handler
#   see: https://github.com/ansible/ansible/issues/14270
#
- name: Report commit status to GitHub
  command: >+
    curl -X POST \
      -H "Authorization: token {{ GITHUB_STATUS_TOKEN }}" \
      -H "Content-type: application/json" -d '
         {
           "state" : "success",
           "description" : "{{ github_commit_status_description | default('Deployed') }}",
           "context" : "{{ github_commit_status_context | default('continuous-integration/ansible') }}"
         }' \
      https://api.github.com/repos/{{ github_repo_owner }}/{{ github_repo_name }}/statuses/{{ github_commit }}

  when: ENVIRONMENT != 'local' and github_statuses_enabled
  run_once: true
  ignore_errors: true
  delegate_to: 127.0.0.1
