---
- name: "Trigger chatops handler"
  debug: msg="Trigger chatops handler"
  changed_when: true
  notify: "Report to Chatops"
  run_once: true


# github statuses disabled by default
- name: set default for github statuses to disabled
  set_fact: github_statuses_enabled=false

- name: Check required variables to report commit statuses to GitHub
  set_fact: github_statuses_enabled=true
  when:
    - github_repo_name is defined and github_repo_name
    - github_repo_owner is defined and github_repo_owner
    - github_commit is defined and github_commit
    - github_deployment_env_url is defined and github_deployment_env_url
    - GITHUB_STATUS_TOKEN is defined and GITHUB_STATUS_TOKEN

- block:
  - include_tasks: github_deployment_create.yml

  # Trigger github status report
  - include_tasks: github_status_report.yml

  # Trigger github deployment report
  - include_tasks: github_deployment_success.yml

  run_once: true
  when: github_statuses_enabled
